{{- $services := list "frontend" "backend" -}}
{{- $root := $ }}  
{{- range $i, $svc := $services }}
 {{- $service := index $root.Values $svc }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include (print "demo-app." $svc ".serviceName") $ }}
  labels:
    {{- with $service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ $service.service.type }}
  ports:
    - port: {{ $service.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- with $service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
