userPasswords:
    - name: ENC[AES256_GCM,data:rWwVdWeED7w=,iv:IoDTt0WGTXODMn1Q+FxOgUN068Qh9KPCuOtU1FwygfI=,tag:1SEsBUIPYO6wuLJfW+mvyQ==,type:str]
      password: ENC[AES256_GCM,data:lpxIRFKUQ+B4VVM=,iv:0XAv2JBH50OG1cVxZNzy7pNH7DaydVvthMiWCu9T7XI=,tag:n6MtpsMwRNy+togf4ttCKg==,type:str]
    - name: ENC[AES256_GCM,data:38wtWhbjyA==,iv:CJpZZ3eHrJxGBgLnotqEwvUVQyIUKtDRMqH90Vn2XcI=,tag:rMKqTkpdrBcI4dXAfGvSHQ==,type:str]
      password: ENC[AES256_GCM,data:QWd+9Rli/zr174lZ,iv:cvBRgKP2MDtn+VHJUuIog30vVBKAgeuU3PBl3j+uO0g=,tag:P6YPhLMJHGyWoXJfQHUoOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15svnvtd9krgaxclertawnrr5jhqm2qy5dzp9g93qv2n0mnqlggcs8hr0s2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TndkYytkbFYxUHZnMkFw
            emZCSVJmUjlGeGpWTEpvU3BCN0xodU9QTDBNClF5V01wTUp6T25TbHJaVWU5MVFX
            bSt0aHVZNCtjUmpMWGg3aDVzV25YTjAKLS0tICtnL3JsV2pXZVpqeUFFNllxNVJz
            TkFIVEkrMksrYXNtNUlwMHVDb0tMcHMKY9Pe/sGfCotxO3fQBZzmngdsPqCWOQ8e
            WXqjfQnwKgXohVcqswZ9x5DPQJO9JXUOeJylo8HJhilz/eC0Lt34pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-08T08:21:32Z"
    mac: ENC[AES256_GCM,data:O+YtVR4p/LjN/rrrJfXLFXQ7XFV6q72g0g81pxrSOykvaGsKamCOis9HEfai0OqEnXbQWq1Cnu9WSIYYJbJlJ6M9Rvw9TkwfAMo5ND0SJfIiKpA0AGBQDfOSY4wlZD/fZC5/wZRJ2IVhhARH+wErCFLf2AQGNZ1A3keBnL7sFbA=,iv:m189wGt7m5Q5XwrCwB/1RdkwlUDOszX90oHqRry372M=,tag:uWYbyFVkAE6ITwoCfDf91w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
