{{- range $i, $user := .Values.userPasswords }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "s-mongo-%s-password" $user.name | trunc 63 | trimSuffix "-" }}
type: Opaque
stringData:
  password: {{ $user.password }}
{{- end }}
